name: Compatability Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        angular-version:
          - 11.0.x
          - 11.1.x
          - 11.2.x
          - 12.0.x
          - 12.1.x
          - 12.2.x
          - 13.0.x

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Use Angular ${{ matrix.angular-version }}
        uses: ngworker/angular-versions-action@v4
        with:
          angular-version: ${{ matrix.angular-version }}
      - run: npm install  --legacy-peer-deps
      - run: npm run build
