name: API Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  angular-doc:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: NodeJS Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            frontend/node_modules
            lthn/node_modules
          key: ${{ runner.os }}-nodejs-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nodejs-
      - run: npm install
      - run: cd frontend && npm run doc
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation
